[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
sha3 = "0.10.8"
serde = { version = "1.0", features = ["derive"] } 